import type { Theme } from "@/models/Theme";

export let themeOptions: Theme[] = [
  {
    id: 0,
    name: 'Red',
    bg: 'bg-red-400',
    bgHover: 'bg-red-500',
    bgActive: 'bg-red-600',
    text: 'text-red-400',
    borderColor: 'border-color-400',
  },
  {
    id: 1,
    name: 'Orange',
    bg: 'bg-orange-400',
    bgHover: 'bg-orange-500',
    bgActive: 'bg-orange-600',
    text: 'text-orange-400',
    borderColor: 'border-color-400',
  },
  {
    id: 2,
    name: 'Amber',
    bg: 'bg-amber-400',
    bgHover: 'bg-amber-500',
    bgActive: 'bg-amber-600',
    text: 'text-amber-400',
    borderColor: 'border-color-400',
  },
  {
    id: 3,
    name: 'Yellow',
    bg: 'bg-yellow-400',
    bgHover: 'bg-yellow-500',
    bgActive: 'bg-yellow-600',
    text: 'text-yellow-400',
    borderColor: 'border-color-400',
  },
  {
    id: 4,
    name: 'Lime',
    bg: 'bg-lime-400',
    bgHover: 'bg-lime-500',
    bgActive: 'bg-lime-600',
    text: 'text-lime-400',
    borderColor: 'border-color-400',
  },
  {
    id: 5,
    name: 'Green',
    bg: 'bg-green-400',
    bgHover: 'bg-green-500',
    bgActive: 'bg-green-600',
    text: 'text-green-400',
    borderColor: 'border-color-400',
  },
  {
    id: 6,
    name: 'Emerald',
    bg: 'bg-emerald-400',
    bgHover: 'bg-emerald-500',
    bgActive: 'bg-emerald-600',
    text: 'text-emerald-400',
    borderColor: 'border-color-400',
  },
  {
    id: 7,
    name: 'Teal',
    bg: 'bg-teal-400',
    bgHover: 'bg-teal-500',
    bgActive: 'bg-teal-600',
    text: 'text-teal-400',
    borderColor: 'border-color-400',
  },
  {
    id: 8,
    name: 'Cyan',
    bg: 'bg-cyan-400',
    bgHover: 'bg-cyan-500',
    bgActive: 'bg-cyan-600',
    text: 'text-cyan-400',
    borderColor: 'border-color-400',
  },
  {
    id: 9,
    name: 'Sky',
    bg: 'bg-sky-400',
    bgHover: 'bg-sky-500',
    bgActive: 'bg-sky-600',
    text: 'text-sky-400',
    borderColor: 'border-color-400',
  },
  {
    id: 10,
    name: 'Blue',
    bg: 'bg-blue-400',
    bgHover: 'bg-blue-500',
    bgActive: 'bg-blue-600',
    text: 'text-blue-400',
    borderColor: 'border-color-400',
  },
		{
    id: 11,
    name: 'Indigo',
    bg: 'bg-indigo-400',
    bgHover: 'hover:bg-indigo-500',
    bgActive: 'active:bg-indigo-600',
    text: 'text-indigo-400',
    borderColor: 'border-color-400'
  },
  {
    id: 12,
    name: 'Violet',
    bg: 'bg-violet-400',
    bgHover: 'hover:bg-violet-500',
    bgActive: 'active:bg-violet-600',
    text: 'text-violet-400',
    borderColor: 'border-color-400'
  },
  {
    id: 13,
    name: 'Purple',
    bg: 'bg-purple-400',
    bgHover: 'hover:bg-purple-500',
    bgActive: 'active:bg-purple-600',
    text: 'text-purple-400',
    borderColor: 'border-color-400'
  },
  {
    id: 14,
    name: 'Fuchsia',
    bg: 'bg-fuchsia-400',
    bgHover: 'hover:bg-fuchsia-500',
    bgActive: 'active:bg-fuchsia-600',
    text: 'text-fuchsia-400',
    borderColor: 'border-color-400'
  },
  {
    id: 15,
    name: 'Pink',
    bg: 'bg-pink-400',
    bgHover: 'hover:bg-pink-500',
    bgActive: 'active:bg-pink-600',
    text: 'text-pink-400',
    borderColor: 'border-color-400'
  },
  {
    id: 16,
    name: 'Rose',
    bg: 'bg-rose-400',
    bgHover: 'hover:bg-rose-500',
    bgActive: 'active:bg-rose-600',
    text: 'text-rose-400',
    borderColor: 'border-color-400'
  }
];